version: "4"

services:
  frontend:
    build: ./frontend
    container_name: todo_list_frontend
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    container_name: todo_list_backend
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true